sudo: true
dist: xenial

branches:
  only:
  - master

language: python

python:
- '3.6'

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libfop-java libbatik-java graphviz
- wget http://security.ubuntu.com/ubuntu/pool/universe/p/plantuml/plantuml_8039-1_all.deb
- sudo dpkg -i plantuml_8039-1_all.deb

install:
- pip install Sphinx>=1.6.3
- pip install -r requirements.txt

script:
- sphinx-build source build
