---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "renga.fullname" . }}
  labels:
    app: {{ template "renga.name" . }}
    chart: {{ template "renga.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  init.sh: |-
    set -ex
    apt-get update -y
    apt-get install -y curl

    BASE_URL={{ .Values.ui.baseUrl | default (printf "%s://%s" (include "renga-ui.protocol" .) .Values.global.renga.domain) | quote }}
    GITLAB_URL={{ .Values.ui.gitlabUrl | default (printf "%s://gitlab.%s" (include "renga-ui.protocol" .) .Values.global.renga.domain) | quote }}

    psql -v ON_ERROR_STOP=1 <<-EOSQL
        DELETE FROM oauth_applications WHERE uid='renga-ui';
        INSERT INTO oauth_applications (name, uid, scopes, redirect_uri, secret, trusted)
        VALUES ('renga-ui', 'renga-ui', 'api read_user', '$BASE_URL/login/redirect/gitlab', 'no-secret-needed', 'true');

        DELETE FROM personal_access_tokens WHERE user_id='1' AND name='managed storage token';
        INSERT INTO personal_access_tokens ( user_id, token, name, revoked, expires_at, created_at, updated_at, scopes, impersonation)
        VALUES ( '1', '${GITLAB_SUDO_TOKEN}', 'managed sudo token', 'f', NULL, NOW(), NOW(), E'--- \n- api\n- read_user\n- sudo\n- read_registry', 'f');
    EOSQL
